Remove postcards for gold offer from /about/gold
reddit/reddit-plugin-gold pull request #63
Opened 2016-09-16 21:14 UTC by powerlanguage

👓  @Deimos 

![gold-page](https://cloud.githubusercontent.com/assets/1231913/18601469/db73bd0e-7c17-11e6-8db7-225eb4a275dd.png)

2016-09-16 21:18 UTC, Deimos commented on reddit_gold/public/static/css/gold.less
> -            background: url(../gold/reddit-gold.png) no-repeat;
I think you can delete this reddit-gold.png as well.

2016-09-16 21:21 UTC, Deimos commented on reddit_gold/public/static/css/gold.less
> -        background: url(../gold/sticker.png) no-repeat;
sticker.png should be able to be deleted too.

2016-09-16 21:26 UTC, Deimos requested changes
Looks good, just a couple more things that can be deleted too.

2016-09-16 21:26 UTC, Deimos commented
:nail_care:

2016-09-19 02:56 UTC, powerlanguage commented
💇

2016-09-19 17:00 UTC, Deimos commented
:fish:

2016-09-19 17:01 UTC, Deimos approved these changes

2016-09-20 19:18 UTC, merged